# Generated by Django 4.2.29 on 2026-04-06 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Asia Decor Samarkand', max_length=200)),
                ('tagline', models.CharField(default='Yaqinlaringizga quvonch baxsh eting', max_length=300)),
                ('bio', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agency/')),
                ('phone1', models.CharField(blank=True, default='', max_length=20)),
                ('phone2', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('payment_card', models.CharField(blank=True, default='8600 0000 0000 0000', help_text='Karta raqami', max_length=30)),
                ('payment_card_owner', models.CharField(blank=True, default='', max_length=100)),
                ('advance_percent', models.IntegerField(default=30, help_text="Oldindan to'lov foizi (%)")),
                ('telegram_link', models.URLField(blank=True, default='', help_text='https://t.me/channelname')),
                ('instagram_link', models.URLField(blank=True, default='', help_text='https://instagram.com/...')),
                ('youtube_link', models.URLField(blank=True, default='', help_text='https://youtube.com/...')),
                ('tiktok_link', models.URLField(blank=True, default='', help_text='https://tiktok.com/@...')),
                ('facebook_link', models.URLField(blank=True, default='', help_text='https://facebook.com/...')),
            ],
            options={
                'verbose_name': 'Agentlik sozlamalari',
                'verbose_name_plural': 'Agentlik sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('tabrik', 'Tabriklar'), ('bezak', "To'y bezaklari"), ('sarpo', 'Sarpo-sandiq bezaklari')], default='tabrik', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('price_label', models.CharField(default="so'm", help_text="Masalan: so'm, $ yoki 'dan boshlab'", max_length=50)),
                ('cover_image', models.ImageField(upload_to='services/covers/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['service_type', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/')),
                ('sort_order', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.serviceitem')),
            ],
            options={
                'verbose_name': 'Xizmat rasmi',
                'verbose_name_plural': 'Xizmat rasmlari',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=200)),
                ('service_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=20)),
                ('delivery_address', models.TextField()),
                ('birthday_person_name', models.CharField(max_length=200)),
                ('birthday_person_age', models.IntegerField()),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('full', "To'liq to'lov"), ('advance', "Oldindan to'lov (zaklad)")], default='full', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('confirmed', 'Tasdiqlangan'), ('in_progress', 'Jarayonda'), ('completed', 'Bajarilgan'), ('cancelled', 'Bekor qilingan')], default='new', max_length=20)),
                ('telegram_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.serviceitem')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
